export const SHOW_LOADING = "SHOW_LOADING_NOW_SHOWING";
export const HIDE_LOADING = "HIDE_LOADING_NOW_SHOWING";
export const SET_ERROR = "SET_ERROR_NOW_SHOWING";
export const SET_DATA = "SET_DATA_NOW_SHOWING";
export const SET_MESSAGE = "SET_MESSAGE_NOW_SHOWING";
export const RESET = "RESET_NOW_SHOWING";
