export const SHOW_LOADING = "SHOW_LOADING_NOW_SHOWING";
export const HIDE_LOADING = "HIDE_LOADING_NOW_SHOWING";
export const SET_ERROR = "SET_ERROR_NOW_SHOWING";
export const SET_NOW_SHOWING = "SET_NOW_SHOWING";
export const SET_MOVIE_BY_GENRE = "SET_MOVIE_BY_GENRE";
export const SET_MESSAGE = "SET_MESSAGE_NOW_SHOWING";
export const RESET = "RESET_NOW_SHOWING";
